# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Client' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#pod 'ProtocolBuffers-Swift','~> 4.0.6'
pod 'SwiftProtobuf'

end
